// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Article author documents
 */
interface ArticleAuthorDocumentData {
  /**
   * Author Name field in *Article author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_author.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author role field in *Article author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_author.author_role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author image field in *Article author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_author.author_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_image: prismic.ImageField<never>;
}

/**
 * Article author document from Prismic
 *
 * - **API ID**: `article_author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleAuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleAuthorDocumentData>,
    "article_author",
    Lang
  >;

/**
 * Content for Article category documents
 */
interface ArticleCategoryDocumentData {
  /**
   * Category name field in *Article category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.category_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_name: prismic.KeyTextField;
}

/**
 * Article category document from Prismic
 *
 * - **API ID**: `article_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleCategoryDocumentData>,
    "article_category",
    Lang
  >;

type BlogArticleDocumentDataSlicesSlice =
  | TestimonialsSlice
  | FaqSlice
  | CtaSlice;

/**
 * Content for Blog Article documents
 */
interface BlogArticleDocumentData {
  /**
   * Title field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Author field in *Blog Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Excerpt field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Featured Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Category field in *Blog Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: prismic.ContentRelationshipField<"blog_category">;

  /**
   * Slice Zone field in *Blog Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Article document from Prismic
 *
 * - **API ID**: `blog_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogArticleDocumentData>,
    "blog_article",
    Lang
  >;

interface FooterDocumentData {}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = NavigationLinksSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * CTAs field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.ctas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Link"
    >
  >;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice> /**
   * Logo position field in *Header*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: header.logo_position
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */;
  logo_position: prismic.BooleanField;

  /**
   * Menu position field in *Header*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: header.menu_position
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  menu_position: prismic.SelectField<"center" | "left" | "right", "filled">;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | LogoSlice
  | HeroSlice
  | TestimonialsSlice
  | CtaSlice
  | FaqSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LandingDocumentDataSlicesSlice = TestimonialsSlice | FaqSlice | CtaSlice;

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
  /**
   * Slice Zone field in *Landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Company name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_name
   * - **Tab**: Company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleAuthorDocument
  | ArticleCategoryDocument
  | BlogArticleDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | LandingDocument
  | SettingsDocument;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Two column → Primary*
 */
export interface CtaSliceTwoColumnPrimary {
  /**
   * Title field in *Cta → Two column → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.twoColumn.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Cta → Two column → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.twoColumn.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Two column → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.twoColumn.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;
}

/**
 * Two column variation for Cta Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Heading left, description and buttons right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceTwoColumn = prismic.SharedSliceVariation<
  "twoColumn",
  Simplify<CtaSliceTwoColumnPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceTwoColumn;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Faq → Default → Primary → Grp*
 */
export interface FaqSliceDefaultPrimaryGrpItem {
  /**
   * Question field in *Faq → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Faq → With Footer → Primary → Grp*
 */
export interface FaqSliceVariation1PrimaryGrpItem {
  /**
   * Question field in *Faq → With Footer → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → With Footer → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Faq → Variation 2 → Primary → Grp*
 */
export interface FaqSliceVariation2PrimaryGrpItem {
  /**
   * Question field in *Faq → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Button field in *Faq → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Contact
   * - **API ID Path**: faq.default.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Grp field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Faq → With Footer → Primary*
 */
export interface FaqSliceVariation1Primary {
  /**
   * Title field in *Faq → With Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → With Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Faq → With Footer → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceVariation1PrimaryGrpItem>>;

  /**
   * Title - Foot field in *Faq → With Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.title_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_foot: prismic.RichTextField;

  /**
   * Text - Foot field in *Faq → With Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.txt_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt_foot: prismic.RichTextField;

  /**
   * Button field in *Faq → With Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * With Footer variation for Faq Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<FaqSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *Faq → Variation 2 → Primary*
 */
export interface FaqSliceVariation2Primary {
  /**
   * Title field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceVariation2PrimaryGrpItem>>;

  /**
   * Title - foot field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.title_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_foot: prismic.RichTextField;

  /**
   * Text - Foot field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.txt_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt_foot: prismic.RichTextField;

  /**
   * Button field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Variation 2 variation for Faq Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<FaqSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation =
  | FaqSliceDefault
  | FaqSliceVariation1
  | FaqSliceVariation2;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → With background image → Primary*
 */
export interface HeroSliceWithBackgroundImagePrimary {
  /**
   * Title field in *Hero → With background image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → With background image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Hero → With background image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Background image field in *Hero → With background image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withBackgroundImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * With background image variation for Hero Slice
 *
 * - **API ID**: `withBackgroundImage`
 * - **Description**: Centered hero with full-bleed background image and overlay
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceWithBackgroundImage = prismic.SharedSliceVariation<
  "withBackgroundImage",
  Simplify<HeroSliceWithBackgroundImagePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithBackgroundImage;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Logo → Default → Primary → Logos*
 */
export interface LogoSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *Logo → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * Heading field in *Logo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Logos field in *Logo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<LogoSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo strip with heading and repeatable logo images
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

/**
 * Primary content in *NavigationLinks → Default → Primary*
 */
export interface NavigationLinksSliceDefaultPrimary {
  /**
   * Link field in *NavigationLinks → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_links.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for NavigationLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationLinksSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *NavigationLinks → With sublinks → Primary*
 */
export interface NavigationLinksSliceWithSublinksPrimary {
  /**
   * Link field in *NavigationLinks → With sublinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_links.withSublinks.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Sublinks field in *NavigationLinks → With sublinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_links.withSublinks.primary.sublinks
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sublinks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * With sublinks variation for NavigationLinks Slice
 *
 * - **API ID**: `withSublinks`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationLinksSliceWithSublinks = prismic.SharedSliceVariation<
  "withSublinks",
  Simplify<NavigationLinksSliceWithSublinksPrimary>,
  never
>;

/**
 * Slice variation for *NavigationLinks*
 */
type NavigationLinksSliceVariation =
  | NavigationLinksSliceDefault
  | NavigationLinksSliceWithSublinks;

/**
 * NavigationLinks Shared Slice
 *
 * - **API ID**: `navigation_links`
 * - **Description**: NavigationLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationLinksSlice = prismic.SharedSlice<
  "navigation_links",
  NavigationLinksSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Grp*
 */
export interface TestimonialsSliceDefaultPrimaryGrpItem {
  /**
   * Rate field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 5
   * - **API ID Path**: testimonials.default.primary.grp[].rate
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  rate: prismic.SelectField<"5" | "4", "filled">;

  /**
   * Quote field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Image field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[].img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Author field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Company field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Position, Company name
   * - **API ID Path**: testimonials.default.primary.grp[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleAuthorDocument,
      ArticleAuthorDocumentData,
      ArticleCategoryDocument,
      ArticleCategoryDocumentData,
      BlogArticleDocument,
      BlogArticleDocumentData,
      BlogArticleDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceTwoColumnPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceTwoColumn,
      FaqSlice,
      FaqSliceDefaultPrimaryGrpItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation1PrimaryGrpItem,
      FaqSliceVariation1Primary,
      FaqSliceVariation2PrimaryGrpItem,
      FaqSliceVariation2Primary,
      FaqSliceVariation,
      FaqSliceDefault,
      FaqSliceVariation1,
      FaqSliceVariation2,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceWithBackgroundImagePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithBackgroundImage,
      LogoSlice,
      LogoSliceDefaultPrimaryLogosItem,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
      NavigationLinksSlice,
      NavigationLinksSliceDefaultPrimary,
      NavigationLinksSliceWithSublinksPrimary,
      NavigationLinksSliceVariation,
      NavigationLinksSliceDefault,
      NavigationLinksSliceWithSublinks,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryGrpItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
