// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  logo: dynamic(() => import("./Logo")),
  navigation_links: dynamic(() => import("./NavigationLinks")),
  testimonials: dynamic(() => import("./Testimonials")),
};
